[package]
name = "toykv"
version = "0.1.0"
edition = "2021"

[dev-dependencies]
tempfile = "3.10.0"

[dependencies]
fastrand = "2.3.0"
serde = {version = "1.0.219", features = ["derive"]}
serde_json = "1.0.140"


